version: 2.1

orbs:
  codecov: codecov/codecov@3.2.5
  terraform: circleci/terraform@3.2.1

jobs:
  test:
    docker:
      - image: cimg/node:lts
    steps:
      - setup_remote_docker:
          version: 20.10.23
      - checkout
      - run:
          name: "Perform clean install and security audit"
          command: npm ci
      - run:
          name: "Run tests with coverage"
          command: npm test
      - run:
          name: "Create a tarball from a package"
          command: npm pack
      - codecov/upload:
          xtra_args: "--nonZero"

workflows:
  simple:
    jobs:
      - test
